version: '3'
services:
  rabbitmq:
    container_name: rmq
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: on-failure
  bugs_bunny:
        container_name: rmq-ft
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
            - rmq-ft-node-modules:/app/node_modules
        environment:
          CONSUMER_ID: 'bugs-bunny'
        depends_on:
            - rabbitmq
        restart: on-failure
volumes:
  rmq-ft-node-modules:
